# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 466739b70b634d5e5a173b99c290a257c9526133b09eca551100845b97888c4d428a29e45c79352303e3a9ac5962986b84033aa95bdd1b1332c233ded4917cb2

test:
  secret_key_base: 6512937362c41b602e2568cdd3974b23b3b94f263dc96da43051879d416aab06a9b86cff61d22898ce1a2cbe916e2e1684e7943790e9ba40a9a768bb9686fa85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
